---
title: "Options"
output: 
  html_notebook: 
    theme: united
---

# Black and Scholes option model


```{r}
library(tidyverse)
library(plotly)

option_prm <- function(S, X, t, r, sigma, put = FALSE) {

f <- 1 - put * 2
u <- 1/(sigma*t^0.5)

v <- log(S/X)

x <- (r + sigma^2 / 2) * t

d1 <- u * (v + x)

d2 <- d1 - (1/u)

C <- f * pnorm(f * d1) * S - f * pnorm(f * d2) *  X * exp(-1 * r * t)

return(C)

}

S <- 20
X <- 22
t <- 90/365
r <- 0.05
sigma <- 0.1

call_spot <- data.frame(spot = seq(S-10, S+10, by=0.1)) %>% mutate(call_value = option_prm(S = spot, X = X, t = t, r = r, sigma = sigma, put = FALSE), lbound = (spot > X) * (spot - X))

n <- ggplot(call_spot) +
  geom_line(aes(x = spot, y = call_value), color = "skyblue") +
  geom_line(aes(x = spot, y = lbound), color = "tomato")
ggplotly(n, width = 800)

option_prm(S = S, X = X, t = t, r = r, sigma = sigma, put = TRUE)
```

# Option pay-off

```{r}

pay_off_vals <- function(premium, S, X, put = FALSE) {
  
  lbound <- max(0, S - 10)
  ubound <- S + 10
  x <- seq(lbound, ubound)
  y <- (!put) * (x > X) * (x - X) + put * (x < X) * (X - x) - premium
  
  return(data.frame(x, y))
  
}
S <- 42
X <- 42
t <- 365/365
r <- 0.05
sigma <- 0.1

call_prm <- option_prm(S = S, X = X, t = t, r = r, sigma = sigma)
put_prm <- option_prm(S = S, X = X, t = t, r = r, sigma = sigma, put = TRUE)

call_pay <- pay_off_vals(premium = call_prm, S = S, X = X)
put_pay <- pay_off_vals(premium = put_prm, S = S, X = X, put = TRUE)
put_call <- data.frame(spot = call_pay$x, call = call_pay$y, put = put_pay$y) %>% mutate(call_minus_put = call - put)

p <- ggplot(put_call) +
  geom_line(aes(x = spot, y = call), color = "steelblue") +
  geom_line(aes(x = spot, y = -put), color = "tomato") +
  geom_line(aes(x = spot, y = call_minus_put), color = "turquoise") +
  xlab("spot") + ylab("pay off")
ggplotly(p, width = 800)

X - X * exp(-1 * r * t)
```

# Put-call parity

```{r}
S <- 42
X <- 45
t <- 365/365
r <- 0.05
sigma <- 0.1

C <- option_prm(S=S, X=X, t=t, r=r, sigma=sigma)
P <- option_prm(S=S, X=X, t=t, r=r, sigma=sigma, put=TRUE)
X_PV <- X*exp(-r*t)

cat("C =", C, ", P =", P, ", X_PV =", X_PV, "=> C + X_PV - P =", C + X_PV - P, "= S")
```

